### ISSUE TITLE
Winpinator unable to transfer large folder between Windows machines (Unexpected Error)

### ISSUE THREAD

**Issue by MinuteNewt** [swiszczoo/winpinator#16]
Hi. 

I tried sending my music folder (1 GB) to my other Windows computer, but at around 200 MB got an error message, "Unexpected error" or something like that. I tried using the 64-bit version of Winpinator on both machines, didn't help. Used the network interface that said "Ethernet" on both computers. Didn't help. I don't know if I can provide more details, I'm not very good at networking things.

**Comment by swiszczoo** [comment]
Hi, it's very hard to tell what's going wrong in your case. However, if Winpinator successfully transfers 200MB and then an error occurs, it's most likely not a networking error, rather something unusual in your music folder (a file that cannot be read?). I tried sending my own music directory because I thought it might fail at some point due to hidden cover art files that Windows creates, but I can't reproduce it. 

What you can check is to right-click the failed transfer on your sending machine and select `Show list of transferred files`. This list should show only successfully transferred files in alphabetical order. Try to find any anomalies in the list, as it might give us some clues (e.g. if the list suddenly ends on file with name `pa*****.mp3`, the name of that problematic file will most likely also start with  `p` or maybe `q` and so on).

If that won't help, I'll compile a special version of Winpinator, logging all filesystem activity during transfer to some *.log file. Then I'll ask you to install it - this should give a definitive answer on what's going wrong in your case.

**Comment by MinuteNewt** [comment]
> Hi, it's very hard to tell what's going wrong in your case. However, if Winpinator successfully transfers 200MB and then an error occurs, it's most likely not a networking error, rather something unusual in your music folder (a file that cannot be read?). I tried sending my own music directory because I thought it might fail at some point due to hidden cover art files that Windows creates, but I can't reproduce it.
> 
> What you can check is to right-click the failed transfer on your sending machine and select `Show list of transferred files`. This list should show only successfully transferred files in alphabetical order. Try to find any anomalies in the list, as it might give us some clues (e.g. if the list suddenly ends on file with name `pa*****.mp3`, the name of that problematic file will most likely also start with `p` or maybe `q` and so on).
> 
> If that won't help, I'll compile a special version of Winpinator, logging all filesystem activity during transfer to some *.log file. Then I'll ask you to install it - this should give a definitive answer on what's going wrong in your case.

Hi. You're right, it was a character that made the transfer fail: either an apostrophe ' or a set of parentheses ( ) - my file name had both so I can't tell which it was. Solved!
